name: CH3 Test

on:
  push:
    paths:
      - 'src/CH3/*'
      - '.github/workflows/ch3.yml'
  pull_request:
    paths:
      - 'src/CH3/*'
      - '.github/workflows/ch3.yml'

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: docker compose up and build
        run: docker-compose up --build

